# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Nom')),
                ('number', models.IntegerField(default=1, verbose_name='Numero')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='mask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masks.Mask'),
        ),
    ]
