# Generated by Django 2.1.7 on 2019-03-27 17:14

from django.db import migrations, models
import masks.models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mask',
            name='active',
        ),
        migrations.AddField(
            model_name='mask',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='mask',
            name='condition',
            field=models.CharField(choices=[('new', 'new'), ('good', 'good'), ('bad', 'bad'), ('broken', 'broken')], default='new', max_length=7, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='mask',
            name='idNumber',
            field=models.CharField(default=masks.models.default_id_number, max_length=50, unique=True, validators=[masks.models.validate_int], verbose_name='id. number'),
        ),
    ]
