# Generated by Django 2.1.7 on 2019-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0002_auto_20190327_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='area',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Area'),
        ),
    ]
