# Generated by Django 2.0.2 on 2019-09-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0003_auto_20190328_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask',
            name='condition',
            field=models.CharField(choices=[('Nouveau', 'Nouveau'), ('Bon', 'Bon'), ('Mauvais', 'Mauvais'), ('Cassé', 'Cassé')], default='new', max_length=7, verbose_name='Condition'),
        ),
    ]
